# Generated by Django 2.0.7 on 2020-11-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201110_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='album_logo',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
