# Generated by Django 2.0.7 on 2020-11-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_album_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='album_logo',
        ),
    ]
