# Generated by Django 2.0.7 on 2020-11-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='album_logo',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
