# Generated by Django 3.1.3 on 2020-11-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='dog.jpg', upload_to='profile_pics'),
        ),
    ]
