# Generated by Django 3.1.3 on 2020-11-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201116_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/dog.jpg', upload_to='profile_pics'),
        ),
    ]
