# Generated by Django 3.1.3 on 2020-11-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201116_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='dog.jpg', upload_to='profile_pics'),
        ),
    ]
