# Generated by Django 3.1.3 on 2020-11-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201116_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/dog.jpg', upload_to='profile_pics'),
        ),
    ]
