# Generated by Django 3.1.3 on 2020-11-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20201116_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.JPG', upload_to='profile_pics'),
        ),
    ]
