# Generated by Django 3.1.3 on 2020-11-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20201116_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
