# Generated by Django 3.1.3 on 2020-11-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20201118_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to='profile_pics'),
        ),
    ]
