# Generated by Django 3.1.3 on 2020-11-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='painting',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='posts/'),
        ),
    ]
