# Generated by Django 3.1.3 on 2020-11-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_post_painting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='painting',
            field=models.ImageField(max_length=255, null=True, upload_to='posts/'),
        ),
    ]
