# Generated by Django 3.1.3 on 2020-11-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20201123_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='painting',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='posts/'),
        ),
    ]
