# Generated by Django 3.1.3 on 2020-11-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_post_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cropping',
        ),
    ]
