# Generated by Django 3.1.3 on 2020-11-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_post_cropping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post'},
        ),
    ]
