# Generated by Django 3.1.3 on 2020-12-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20201203_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='cropping',
        ),
    ]
