# Generated by Django 3.1.3 on 2020-12-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20201212_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='hotel_Main_Img',
            new_name='Main_Img',
        ),
    ]
