# Generated by Django 3.1.3 on 2021-01-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20201212_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
