# Generated by Django 3.1.3 on 2021-01-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_workshop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='painting',
            field=models.ImageField(max_length=255, null=True, upload_to='posts/'),
        ),
    ]
