# Generated by Django 3.1.3 on 2021-01-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20210121_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', max_length=255, null=True, upload_to='profile_pics'),
        ),
    ]
